### ISSUE TITLE
Definition of <col> element auto-closes parent <colgroup>

### ISSUE THREAD

**Issue by ultraq** [attoparser/attoparser#15]
When investigating [a comment made on an issue against the layout dialect](https://github.com/ultraq/thymeleaf-layout-dialect/issues/138#issuecomment-256840462), I found that the dialect was being given a model that had inserted synthetic close tags for `<colgroup>` elements before each opening `<col>` tag.

![screen shot 2016-10-31 at 9 45 48 pm](https://cloud.githubusercontent.com/assets/1686920/19849725/a0fbbb34-9fb9-11e6-8741-832175a2d22e.png)

I couldn't find anything in the HTML spec to support this behaviour, so I think this is a bug in the configuration of the `<col>` element: https://github.com/attoparser/attoparser/blob/master/src/main/java/org/attoparser/HtmlElements.java#L159

**Comment by danielfernandez** [comment]
Already in `2.0.2-SNAPSHOT`
