### ISSUE TITLE
Incorrect parsing of TEMPLATE tag

### ISSUE THREAD

**Issue by gjdev** [attoparser/attoparser#7]
Attoparser (2.x) defines the TEMPLATE tag as a HtmlHeadCDATAContentElement. This is not in accordance with the HTML5 standard. It is a block element that may contain child elements, even nested TEMPLATE elements etc.
The current behavior makes it impossible to correctly parse documents that use the HTML5 TEMPLATE tag.

**Comment by danielfernandez** [comment]
Agreed. Will modify this before releasing thymeleaf 3.0. Thanks.

**Comment by danielfernandez** [comment]
Updated `2.0.0-SNAPSHOT`
